FROM node:22-bookworm

# Install Python
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv

WORKDIR /app

COPY . .

# Install Backend
WORKDIR /app/deployment/backend
RUN npm install

# Install ML
WORKDIR /app/deployment/ml-service
RUN pip3 install --break-system-packages -r requirements.txt

# Kembali
WORKDIR /app

COPY deployment/start.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 3000
EXPOSE 8000

CMD ["/start.sh"]